const localText = {
    'Add': 'Add',
    'Passwords do not match': 'Passwords do not match',
    'Confirm': 'Confirm',
    'file': 'file',
    'Uploading': 'Uploading',
    'Add Files': 'Add Files',
    'files': 'files',
    'Delete All': 'Delete All',
    'Yes': 'Yes',
    'No': 'No',
    'Cancel': 'Cancel',
    'Submit': 'Submit',
    'Edit': 'Edit',
    'Remove': 'Remove',
    'Download': 'Download',
    'Delete': 'Delete',
    'View Uploaded Files': 'View Uploaded Files',
    'Save': 'Save',
    'Show Files': 'Show Files',
    'This field can not be empty': 'This field can not be empty',
    'Upload Here': 'Upload Here',
}

export default localText