import { AtFormButtonProps } from "./ui/Button.type";
import { AtFormTextBoxProps } from "./ui/TextBox.type";
import { AtFormIntegerTextBoxProps } from "./ui/IntegerTextBox.type";
import { AtFormFloatTextBoxProps } from "./ui/FloatTextBox.type";
import { AtFormComboBoxProps } from "./ui/ComboBox.type";
import { AtFormMultiComboBoxProps } from "./ui/MultiComboBox.type";
import { AtFormDatePickerProps } from "./ui/DatePicker.type";
import { AtFormUploadButtonProps } from "./ui/UploadButton.type";
import { AtFormUploadImageButtonProps } from "./ui/UploadImageButton.type";
import { AtFormFileViewerProps } from "./ui/FileViewer.type";
import { AtFormCascadeComboBoxProps } from "./ui/CascadeComboBox.type";
import { AtFormMultiValueCascadeComboBoxProps } from "./ui/MultiValueCascadeComboBox.type";
import { AtFormCheckBoxProps } from "./ui/CheckBox.type";
import { AtFormSliderProps } from "./ui/Slider.type";
import { AtFormPasswordTextBoxProps } from "./ui/PasswordTextBox.type";
import { AtFormDoublePasswordTextBoxProps } from "./ui/DoublePasswordTextBox.type";
import { AtFormAvatarProps } from "./ui/Avatar.type";
import { AtFormLabelProps } from "./ui/Label.type";
import { AtFormContainerWithTableProps } from "./ui/ContainerWithTable.type";
import { AtFormMultiSelectTextBoxProps } from "./ui/MultiSelectTextBox.type";
import { AtFormTableProps } from "./ui/Table.type";
import { AtFormMultiSelectGridProps } from "./ui/MultiSelectGrid.type";
import { AtFormImageSelectProps } from "./ui/ImageSelect.type";
import { AtFormAdvanceStepperProps } from "./ui/AdvanceStepper.type";
import { AtFormFormProps } from "./ui/Form.type";
import { AtFormColorTextBoxProps } from "./ui/ColorTextBox.type";

export interface AtFormUiTypeMap {
    Button: AtFormButtonProps;
    TextBox: AtFormTextBoxProps;
    IntegerTextBox: AtFormIntegerTextBoxProps;
    FloatTextBox: AtFormFloatTextBoxProps;
    ComboBox: AtFormComboBoxProps;
    MultiComboBox: AtFormMultiComboBoxProps;
    DatePicker: AtFormDatePickerProps;
    UploadButton: AtFormUploadButtonProps;
    UploadImageButton: AtFormUploadImageButtonProps;
    FileViewer: AtFormFileViewerProps;
    CascadeComboBox: AtFormCascadeComboBoxProps;
    MultiValueCascadeComboBox: AtFormMultiValueCascadeComboBoxProps;
    CheckBox: AtFormCheckBoxProps;
    Slider: AtFormSliderProps;
    PasswordTextBox: AtFormPasswordTextBoxProps;
    DoublePasswordTextBox: AtFormDoublePasswordTextBoxProps;
    Avatar: AtFormAvatarProps;
    Label: AtFormLabelProps;
    ContainerWithTable: AtFormContainerWithTableProps;
    MultiSelectTextBox: AtFormMultiSelectTextBoxProps;
    Table: AtFormTableProps;    
    MultiSelectGrid: AtFormMultiSelectGridProps;
    ImageSelect: AtFormImageSelectProps;
    AdvanceStepper: AtFormAdvanceStepperProps;
    Form: AtFormFormProps;
    ColorTextBox: AtFormColorTextBoxProps;
}
