import { ATFormButtonProps } from "./ui/Button.type";
import { ATFormTextBoxProps } from "./ui/TextBox.type";
import { ATFormIntegerTextBoxProps } from "./ui/IntegerTextBox.type";
import { ATFormFloatTextBoxProps } from "./ui/FloatTextBox.type";
import { ATFormComboBoxProps } from "./ui/ComboBox.type";
import { ATFormMultiComboBoxProps } from "./ui/MultiComboBox.type";
import { ATFormDatePickerProps } from "./ui/DatePicker.type";
import { ATFormUploadButtonProps } from "./ui/UploadButton.type";
import { ATFormUploadImageButtonProps } from "./ui/UploadImageButton.type";
import { ATFormFileViewerProps } from "./ui/FileViewer.type";
import { ATFormCascadeComboBoxProps } from "./ui/CascadeComboBox.type";
import { ATFormMultiValueCascadeComboBoxProps } from "./ui/MultiValueCascadeComboBox.type";
import { ATFormCheckBoxProps } from "./ui/CheckBox.type";
import { ATFormSliderProps } from "./ui/Slider.type";
import { ATFormPasswordTextBoxProps } from "./ui/PasswordTextBox.type";
import { ATFormDoublePasswordTextBoxProps } from "./ui/DoublePasswordTextBox.type";
import { ATFormAvatarProps } from "./ui/Avatar.type";
import { ATFormLabelProps } from "./ui/Label.type";
import { ATFormContainerWithTableProps } from "./ui/ContainerWithTable.type";
import { ATFormMultiSelectTextBoxProps } from "./ui/MultiSelectTextBox.type";
import { ATFormTableProps } from "./ui/Table.type";
import { ATFormMultiSelectGridProps } from "./ui/MultiSelectGrid.type";
import { ATFormImageSelectProps } from "./ui/ImageSelect.type";
import { ATFormAdvanceStepperProps } from "./ui/AdvanceStepper.type";
import { ATFormFormProps } from "./ui/Form.type";
import { ATFormColorTextBoxProps } from "./ui/ColorTextBox.type";

export interface ATFormUITypeMap {
    Button: ATFormButtonProps;
    TextBox: ATFormTextBoxProps;
    IntegerTextBox: ATFormIntegerTextBoxProps;
    FloatTextBox: ATFormFloatTextBoxProps;
    ComboBox: ATFormComboBoxProps;
    MultiComboBox: ATFormMultiComboBoxProps;
    DatePicker: ATFormDatePickerProps;
    UploadButton: ATFormUploadButtonProps;
    UploadImageButton: ATFormUploadImageButtonProps;
    FileViewer: ATFormFileViewerProps;
    CascadeComboBox: ATFormCascadeComboBoxProps;
    MultiValueCascadeComboBox: ATFormMultiValueCascadeComboBoxProps;
    CheckBox: ATFormCheckBoxProps;
    Slider: ATFormSliderProps;
    PasswordTextBox: ATFormPasswordTextBoxProps;
    DoublePasswordTextBox: ATFormDoublePasswordTextBoxProps;
    Avatar: ATFormAvatarProps;
    Label: ATFormLabelProps;
    ContainerWithTable: ATFormContainerWithTableProps;
    MultiSelectTextBox: ATFormMultiSelectTextBoxProps;
    Table: ATFormTableProps;    
    MultiSelectGrid: ATFormMultiSelectGridProps;
    ImageSelect: ATFormImageSelectProps;
    AdvanceStepper: ATFormAdvanceStepperProps;
    Form: ATFormFormProps;
    ColorTextBox: ATFormColorTextBoxProps;
}
